### ISSUE TITLE
Create example page wireframes

### ISSUE THREAD

**Issue by mpetrunic** [NodeFactoryIo/metamask-snap-polkadot#17]
Things to display:
- connect button - it's suppose to install metamask snap
   - if metamask is not present display overlay to hide data until metamask is available
   - after connect, replace with public address
- account balance
- account transactions
- button to export private key
- section to sign custom message
   - text area and button sign
- section to transfer
  - to address
  - amount
  - send button

You can use this page to create some wireframe: https://wireframe.cc/

**Comment by irubido** [comment]
-not sure if it should all be on one page, here is first draft
https://wireframe.cc/pro/pp/db980b1eb324620

**Comment by mpetrunic** [comment]
left you some comments

**Comment by irubido** [comment]
public adress, account balance and transactions grouped
https://wireframe.cc/pro/pp/db980b1eb324620
