### ISSUE TITLE
Dcoument snap

### ISSUE THREAD

**Issue by mpetrunic** [NodeFactoryIo/metamask-snap-polkadot#75]
Documentation should be in readme.md and include:
- arhitecture (dapp->adapter->snap-> provider) graph
- InjectedExtension additional api
- document available methods and event listening
- example how to add to own dapp (using injectedExtension)

**Comment by MakMuftic** [comment]
@mpetrunic You can check [finalized documentation](https://github.com/NodeFactoryIo/metamask-snap-polkadot/wiki)

**Comment by mpetrunic** [comment]
Seems fine, open PR with link to wiki in readme
