### ISSUE TITLE
Snap not working because of chain upgrades

### ISSUE THREAD

**Issue by mpetrunic** [NodeFactoryIo/metamask-snap-polkadot#95]
- try to update polkadot libraries
- make sure everything works as expected

Hopefully, you won't encounter ses issues, otherwise we will have to deal with that :fortune_cookie:

**Comment by MakMuftic** [comment]
As we encountered SES issues, we are waiting for some useful information from this [PR](https://github.com/Agoric/SES-shim/issues/341).
